language: node_js
node_js:
  - "node"
install:
  - npm i -g npm
  - npm ci
script:
  - CI=true npm run test
after_success:
  - cat ./coverage/lcov.info|./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
    - next
cache:
  directories:
    - "$HOME/.npm"
    - "node_modules"